### ISSUE TITLE
Provide connect 4 experience for artwise

### ISSUE THREAD

**Issue by jthoenes** [artwise/artwise#2]
Build a "connect 4" game inside the artwise monitor - meaning if someone gets 4 subsequent builds or a diagonal or vertical line of 4 green builds from the same person, show a "USR wins 4" dialog.

**Comment by birgitta410** [comment]
Done 
https://github.com/artwise/artwise/releases/tag/v0.2

**Comment by jthoenes** [comment]
\o/
